/**
 * Whitepaper: All five disruptions, already shipped by Innovia Systems.
 *
 * Affirmative engagement with McKinsey's "The end of ERP as we know it? Five
 * ways AI is disrupting ERP" (January 2026). We agree with all five and show
 * that, in regulated non-bank lending and leasing, each one reaches the P&L
 * only on a platform that is configured rather than rebuilt, decides the same
 * way every time, and can prove what it did. Executive / consulting register
 * (CXO audience), not engineering.
 *
 * Style rules (enforced):
 *  - No em dashes. Substitute with colon, comma, parens, or sentence split.
 *  - Website voice: first person plural ("we").
 *  - No client, partner, or competitor names. McKinsey named only as the
 *    analysis we agree with, with a link to the source.
 *  - Concrete numbers over adjectives; numbers attributed to McKinsey inline.
 */

import { type AppLocale } from '@/i18n/routing';

interface ContentProps {
  locale: AppLocale;
}

export default function FiveDisruptionsAlreadyShipped({ locale }: ContentProps) {
  switch (locale) {
    case 'ro':
      return <Ro />;
    case 'de':
      return <De />;
    case 'fr':
      return <Fr />;
    case 'it':
      return <It />;
    default:
      return <En />;
  }
}

function En() {
  return (
    <div className="prose-paper">
      <p>McKinsey&apos;s January 2026 analysis <a href="https://www.mckinsey.com/capabilities/mckinsey-technology/our-insights/the-end-of-erp-as-we-know-it-five-ways-ai-is-disrupting-erp" target="_blank" rel="noopener noreferrer">The end of ERP as we know it? Five ways AI is disrupting ERP</a> is the clearest read on where AI changes the economics of the enterprise platform, and we agree with all of it. The prize is large: implementation effort roughly halved, process redesign in days, data migration no longer the long pole, a conversational front door in place of menus, and a system that improves continuously rather than in big-bang releases. The catch sits in the same analysis. Firms that put AI into the core lift EBIT by about 5 percent, yet only around 40 percent of organisations capture any enterprise-level value at all. The value is real, and most of it is being left on the table.</p>
      <p>So the question for a lending or leasing business is not whether the five shifts are coming. They are. It is what separates the 40 percent that capture the value from the 60 percent that do not. In our experience the answer is not the AI a firm buys, since everyone can buy the same models. It is the platform the AI runs on. Each shift pays off only where the platform is built to be configured rather than rebuilt, to decide the same way every time, and to prove what it did. That is the platform we already run. Below we take each of McKinsey&apos;s five in turn, agree with it, and name the one condition that decides whether it reaches earnings in a regulated lender.</p>
      <h2>1. Implementation: the speed is real, but it is not evenly available</h2>
      <p>McKinsey is right that AI roughly halves the time and effort to stand a platform up. That prize is not evenly available. It goes to operators whose platform is configured, not rebuilt, for each new institution, because there the AI accelerates a clean, repeatable setup rather than untangling years of custom code. We bring a new lender live by configuring rules on one shared platform, and we run data migration as a standard, repeatable step rather than a project we reinvent each time. So the speed McKinsey describes is our operating model, not an aspiration. On a heavily customised system the same AI only trims the edges, which is exactly why the value concentrates in a minority of firms rather than reaching everyone.</p>
      <h2>2. Process design: in lending, a process is a control, not just a workflow</h2>
      <p>Agents can now propose a target way of working in days, and that is a genuine prize. But in a regulated lender a process carries the institution&apos;s controls: who may approve, who may commit the firm and up to what limit, where a deal must stop. Let an agent design freely and it will quietly remove a control it reads as friction, and the firm has given away something it answers to its regulator for, without anyone deciding to. The prize is safe only when the agent proposes into a model where those controls are fixed and cannot be moved without a recorded, approved decision. That is how we run it: the agent speeds the design up, the platform keeps the controls in place, and every change is logged. Days instead of weeks, with the control posture intact.</p>
      <h2>3. Migration: speed only counts if the data can be trusted afterwards</h2>
      <p>McKinsey is right that AI removes most of the manual data clean-up that slows these programmes down. The catch is that speed only pays if the result can be trusted, because in lending that data drives live credit decisions and provisioning from day one. A migration that is fast but cannot be traced back to source or reproduced is a liability waiting for an examiner. Our platform refuses data that does not fit when it is loaded, and a migrated book can be re-run to reproduce the same classifications and provisions. So the AI shortens the part that used to take months, and the firm arrives with a portfolio it can defend. On a system with no such discipline, the AI speeds up the easy half and the hard half comes back as manual review.</p>
      <h2>4. Natural language: the front door changes, the controls do not</h2>
      <p>The conversational interface turns the elaborate screens that vendors spent two decades making sticky into a commodity, exactly as McKinsey&apos;s bolder reading argues. In a regulated lender it is safe only if it can do nothing a human in that seat could not do: it acts through the platform&apos;s existing, permissioned operations, and a request the user is not allowed to make fails for the assistant just as it would for the person, and is recorded the same way. That is how ours works. The interface became conversational; the controls did not move. That is what lets a lender put the assistant where the revenue is, in origination and servicing, without opening a gap a supervisor would find.</p>
      <h2>5. Continuous improvement: welcome, but it has to be governed</h2>
      <p>Decision logic goes stale, so McKinsey is right that continuous improvement beats waiting for the next big release. But the rules that decide who gets financed, and on what terms, cannot quietly change themselves. A supervisor will ask what the policy decided eighteen months ago, why, and whether it was signed off before it affected a customer. So improvement has to be governed: the AI proposes a change, a person approves it, the platform adopts it as a new, named version, and any past decision can be replayed under the version that applied at the time. That is continuous improvement a regulated lender can actually run, with the stable core McKinsey&apos;s more cautious reading says has to endure.</p>
      <h2>The pattern, and what to do about it</h2>
      <p>The thread through all five is the same. The AI-native future McKinsey describes is not held back by access to AI. It is decided by the platform a firm was running before the AI arrived. The 40 percent that capture the value are the ones whose platform is configured rather than rebuilt, decides the same way every time, and can prove what it did. The rest adopt the AI and see little of it reach earnings.</p>
      <p>So the most useful next step is not an AI shortlist. It is an honest look at your own platform. Are new products configured or coded from scratch. Are your controls built into the platform or written into each process by hand. Can a migration be trusted and traced. Does the conversational layer inherit your permissions unchanged. Can every change to a credit policy be reproduced on demand. The answers to those questions, not the model you license, decide whether AI reaches your bottom line. We did not adopt more AI than the market. We built the platform on which AI pays, and in regulated non-bank lending and leasing that is the difference between capturing the value McKinsey describes and only reading about it.</p>
    </div>
  );
}

function Ro() {
  return (
    <div className="prose-paper">
      <p>Analiza McKinsey din ianuarie 2026 <a href="https://www.mckinsey.com/capabilities/mckinsey-technology/our-insights/the-end-of-erp-as-we-know-it-five-ways-ai-is-disrupting-erp" target="_blank" rel="noopener noreferrer">The end of ERP as we know it? Five ways AI is disrupting ERP</a> este cea mai clară lectură despre felul în care IA schimbă economia platformei de business, și suntem de acord cu tot ce conține. Miza este mare: efortul de implementare redus aproximativ la jumătate, reproiectarea proceselor în câteva zile, migrarea datelor care nu mai este veriga critică, o poartă de intrare conversațională în locul meniurilor și un sistem care se îmbunătățește continuu, nu prin lansări de tip big-bang. Capcana stă în aceeași analiză. Firmele care aduc IA în nucleu își cresc EBIT cu circa 5%, însă doar aproximativ 40% dintre organizații captează vreo valoare reală la nivel de business. Valoarea este reală, iar cea mai mare parte din ea rămâne lăsată pe masă.</p>
      <p>Așadar întrebarea pentru un business de creditare sau de leasing nu este dacă vin cele cinci disrupții. Vin. Întrebarea este ce desparte cele 40% care captează valoarea de cele 60% care nu o captează. Din experiența noastră, răspunsul nu este IA pe care o cumpără o firmă, fiindcă toată lumea poate cumpăra aceleași modele. Este platforma pe care rulează IA. Fiecare disrupție se răsplătește doar acolo unde platforma este construită pentru a fi configurată, nu reconstruită, pentru a decide la fel de fiecare dată și pentru a dovedi ce a făcut. Este platforma pe care o operăm deja. Mai jos luăm pe rând fiecare dintre cele cinci puncte ale McKinsey, suntem de acord cu fiecare și numim singura condiție care decide dacă ajunge la rezultatul financiar într-un creditor reglementat.</p>
      <h2>1. Implementarea: viteza este reală, dar nu este disponibilă uniform</h2>
      <p>McKinsey are dreptate că IA reduce aproximativ la jumătate timpul și efortul de punere în funcțiune a unei platforme. Această miză nu este disponibilă uniform. Ea revine operatorilor a căror platformă este configurată, nu reconstruită, pentru fiecare instituție nouă, fiindcă acolo IA accelerează o configurare curată și repetabilă, în loc să descâlcească ani de cod personalizat. Aducem în producție un creditor nou prin configurarea regulilor pe o singură platformă comună și tratăm migrarea datelor ca pe un pas standard, repetabil, nu ca pe un proiect pe care îl reinventăm de fiecare dată. Astfel, viteza pe care o descrie McKinsey este modelul nostru de operare, nu o aspirație. Pe un sistem puternic personalizat, aceeași IA doar netezește marginile, ceea ce explică tocmai de ce valoarea se concentrează la o minoritate de firme în loc să ajungă la toată lumea.</p>
      <h2>2. Proiectarea proceselor: în creditare, un proces este un control, nu doar un flux de lucru</h2>
      <p>Agenții pot acum să propună un mod de lucru țintă în câteva zile, iar aceasta este o miză autentică. Dar într-un creditor reglementat un proces poartă controalele instituției: cine poate aproba, cine poate angaja firma și până la ce limită, unde trebuie să se oprească o tranzacție. Lasă un agent să proiecteze liber și va elimina în tăcere un control pe care îl citește ca pe o frecare, iar firma a cedat ceva pentru care răspunde în fața supraveghetorului ei, fără ca cineva să fi decis asta. Miza este sigură doar atunci când agentul propune într-un model în care acele controale sunt fixe și nu pot fi mutate fără o decizie înregistrată și aprobată. Așa o operăm: agentul accelerează proiectarea, platforma menține controalele la locul lor, iar fiecare modificare este consemnată. Zile în loc de săptămâni, cu poziția de control intactă.</p>
      <h2>3. Migrarea: viteza contează doar dacă datele pot fi de încredere ulterior</h2>
      <p>McKinsey are dreptate că IA elimină cea mai mare parte a curățării manuale de date care încetinește aceste programe. Capcana este că viteza se răsplătește doar dacă rezultatul poate fi de încredere, fiindcă în creditare acele date conduc deciziile de credit în timp real și provizionarea încă din prima zi. O migrare rapidă, dar care nu poate fi urmărită până la sursă sau reprodusă, este o vulnerabilitate care își așteaptă examinatorul. Platforma noastră refuză datele care nu se potrivesc în momentul încărcării, iar un portofoliu migrat poate fi rulat din nou pentru a reproduce aceleași clasificări și provizioane. Astfel, IA scurtează partea care lua luni întregi, iar firma ajunge cu un portofoliu pe care îl poate apăra. Pe un sistem fără o asemenea disciplină, IA accelerează jumătatea ușoară, iar jumătatea grea revine sub formă de verificare manuală.</p>
      <h2>4. Limbajul natural: poarta de intrare se schimbă, controalele nu</h2>
      <p>Interfața conversațională transformă ecranele elaborate pe care furnizorii consacrați au petrecut două decenii făcându-le greu de părăsit într-o marfă obișnuită, exact cum susține lectura mai îndrăzneață a McKinsey. Într-un creditor reglementat este sigură doar dacă nu poate face nimic din ceea ce un om aflat pe acel scaun nu ar putea face: acționează prin operațiunile existente și permisionate ale platformei, iar o cerere pe care utilizatorul nu are voie să o facă eșuează pentru asistent la fel cum ar eșua pentru persoana respectivă, și este consemnată la fel. Așa funcționează a noastră. Interfața a devenit conversațională; controalele nu s-au mutat. Aceasta este ceea ce îi permite unui creditor să pună asistentul acolo unde sunt veniturile, în originare și în servisare, fără a deschide o breșă pe care un supraveghetor ar găsi-o.</p>
      <h2>5. Îmbunătățirea continuă: binevenită, dar trebuie guvernată</h2>
      <p>Logica de decizie se învechește, așa că McKinsey are dreptate că îmbunătățirea continuă este mai bună decât așteptarea următoarei lansări mari. Dar regulile care decid cine este finanțat și în ce condiții nu se pot schimba singure, în tăcere. Un supraveghetor va întreba ce a decis politica acum optsprezece luni, de ce și dacă a fost aprobată înainte să afecteze un client. Așadar îmbunătățirea trebuie guvernată: IA propune o modificare, o persoană o aprobă, platforma o adoptă ca pe o versiune nouă, denumită, iar orice decizie din trecut poate fi redată sub versiunea care se aplica la momentul respectiv. Aceasta este îmbunătățirea continuă pe care un creditor reglementat o poate opera cu adevărat, cu nucleul stabil despre care lectura mai prudentă a McKinsey spune că trebuie să dăinuie.</p>
      <h2>Tiparul și ce este de făcut în privința lui</h2>
      <p>Firul care leagă toate cele cinci este același. Viitorul nativ-IA pe care îl descrie McKinsey nu este ținut în loc de accesul la IA. Este decis de platforma pe care o firmă o opera înainte ca IA să apară. Cele 40% care captează valoarea sunt cele a căror platformă este configurată, nu reconstruită, decide la fel de fiecare dată și poate dovedi ce a făcut. Restul adoptă IA și văd puțin din ea ajungând la rezultatul financiar.</p>
      <p>Așadar, cel mai util pas următor nu este o listă scurtă de soluții IA. Este o privire onestă asupra propriei platforme. Produsele noi sunt configurate sau scrise în cod de la zero. Controalele voastre sunt încorporate în platformă sau scrise manual în fiecare proces. Poate o migrare să fie de încredere și urmăribilă. Moștenește stratul conversațional permisiunile voastre neschimbate. Poate fi reprodusă la cerere orice modificare a unei politici de credit. Răspunsurile la aceste întrebări, nu modelul pe care îl licențiați, decid dacă IA ajunge la rezultatul vostru financiar. Nu am adoptat mai multă IA decât piața. Am construit platforma pe care IA se răsplătește, iar în creditarea și leasingul non-bancar reglementat aceasta este diferența dintre a capta valoarea pe care o descrie McKinsey și doar a citi despre ea.</p>
    </div>
  );
}

function De() {
  return (
    <div className="prose-paper">
      <p>Die Analyse von McKinsey aus dem Januar 2026 <a href="https://www.mckinsey.com/capabilities/mckinsey-technology/our-insights/the-end-of-erp-as-we-know-it-five-ways-ai-is-disrupting-erp" target="_blank" rel="noopener noreferrer">The end of ERP as we know it? Five ways AI is disrupting ERP</a> ist die klarste Lesart dessen, wo KI die Ökonomie der Unternehmensplattform verändert, und wir stimmen ihr in allen Punkten zu. Der Gewinn ist groß: der Umsetzungsaufwand ungefähr halbiert, Prozessneugestaltung in Tagen, Datenmigration nicht länger der kritische Engpass, ein dialogorientierter Zugang statt Menüs und ein System, das sich kontinuierlich verbessert statt in großen Releases auf einen Schlag. Der Haken steckt in derselben Analyse. Unternehmen, die KI in den Kern bringen, heben das EBIT um etwa 5 Prozent, doch nur rund 40 Prozent der Organisationen erfassen überhaupt einen Wert auf Unternehmensebene. Der Wert ist real, und der größte Teil davon wird liegen gelassen.</p>
      <p>Die Frage für ein Kredit- oder Leasinggeschäft ist also nicht, ob die fünf Verschiebungen kommen. Sie kommen. Es geht darum, was die 40 Prozent, die den Wert erfassen, von den 60 Prozent trennt, die es nicht tun. Nach unserer Erfahrung liegt die Antwort nicht in der KI, die ein Unternehmen kauft, denn jeder kann dieselben Modelle kaufen. Es ist die Plattform, auf der die KI läuft. Jede Verschiebung zahlt sich nur dort aus, wo die Plattform so gebaut ist, dass sie konfiguriert, nicht neu gebaut wird, jedes Mal gleich entscheidet und nachweisen kann, was sie getan hat. Genau diese Plattform betreiben wir bereits. Im Folgenden nehmen wir jeden der fünf Punkte von McKinsey nacheinander auf, stimmen ihm zu und benennen die eine Bedingung, die darüber entscheidet, ob er bei einem regulierten Kreditgeber das Ergebnis erreicht.</p>
      <h2>1. Umsetzung: das Tempo ist real, aber es ist nicht gleichmäßig verfügbar</h2>
      <p>McKinsey hat recht, dass KI die Zeit und den Aufwand für den Aufbau einer Plattform ungefähr halbiert. Dieser Gewinn ist nicht gleichmäßig verfügbar. Er geht an Betreiber, deren Plattform für jede neue Institution konfiguriert, nicht neu gebaut wird, denn dort beschleunigt die KI eine saubere, wiederholbare Einrichtung, statt jahrelangen individuellen Code zu entwirren. Wir bringen einen neuen Kreditgeber live, indem wir Regeln auf einer gemeinsam genutzten Plattform konfigurieren, und wir führen die Datenmigration als standardisierten, wiederholbaren Schritt aus statt als Projekt, das wir jedes Mal neu erfinden. Das Tempo, das McKinsey beschreibt, ist also unser Betriebsmodell, keine Wunschvorstellung. Bei einem stark angepassten System trimmt dieselbe KI nur die Ränder, und genau deshalb konzentriert sich der Wert auf eine Minderheit der Unternehmen, statt alle zu erreichen.</p>
      <h2>2. Prozessgestaltung: im Kreditgeschäft ist ein Prozess eine Kontrolle, nicht nur ein Arbeitsablauf</h2>
      <p>Agenten können heute innerhalb von Tagen eine Zielarbeitsweise vorschlagen, und das ist ein echter Gewinn. Doch bei einem regulierten Kreditgeber trägt ein Prozess die Kontrollen der Institution: wer genehmigen darf, wer das Unternehmen verpflichten darf und bis zu welcher Grenze, wo ein Geschäft anhalten muss. Lässt man einen Agenten frei gestalten, entfernt er stillschweigend eine Kontrolle, die er als Reibung liest, und das Unternehmen hat etwas verschenkt, wofür es sich gegenüber seinem Aufseher verantwortet, ohne dass jemand das entschieden hätte. Der Gewinn ist nur dann sicher, wenn der Agent in ein Modell hinein vorschlägt, in dem diese Kontrollen fixiert sind und nicht ohne eine erfasste, genehmigte Entscheidung verschoben werden können. So betreiben wir es: der Agent beschleunigt die Gestaltung, die Plattform hält die Kontrollen in Kraft, und jede Änderung wird protokolliert. Tage statt Wochen, bei intakter Kontrolllage.</p>
      <h2>3. Migration: Tempo zählt nur, wenn man den Daten danach vertrauen kann</h2>
      <p>McKinsey hat recht, dass KI den größten Teil der manuellen Datenbereinigung beseitigt, die diese Programme verlangsamt. Der Haken ist, dass sich Tempo nur auszahlt, wenn man dem Ergebnis vertrauen kann, denn im Kreditgeschäft steuern diese Daten ab dem ersten Tag laufende Kreditentscheidungen und die Risikovorsorge. Eine Migration, die schnell ist, sich aber nicht bis zur Quelle zurückverfolgen oder reproduzieren lässt, ist ein Risiko, das auf einen Prüfer wartet. Unsere Plattform weist Daten zurück, die beim Laden nicht passen, und ein migrierter Bestand kann erneut durchlaufen werden, um dieselben Klassifizierungen und Risikovorsorgen zu reproduzieren. Die KI verkürzt also den Teil, der früher Monate dauerte, und das Unternehmen kommt mit einem Portfolio an, das es verteidigen kann. Bei einem System ohne eine solche Disziplin beschleunigt die KI die einfache Hälfte, und die schwere Hälfte kommt als manuelle Prüfung zurück.</p>
      <h2>4. Natürliche Sprache: der Zugang ändert sich, die Kontrollen nicht</h2>
      <p>Die dialogorientierte Schnittstelle macht die aufwändigen Bildschirme, die Anbieter zwei Jahrzehnte lang klebrig gemacht haben, zur Massenware, genau wie es die kühnere Lesart von McKinsey vertritt. Bei einem regulierten Kreditgeber ist sie nur dann sicher, wenn sie nichts tun kann, was ein Mensch auf diesem Posten nicht könnte: sie handelt über die bestehenden, berechtigungsgebundenen Vorgänge der Plattform, und eine Anfrage, die der Nutzer nicht stellen darf, scheitert für den Assistenten genauso wie für die Person und wird auf dieselbe Weise erfasst. So funktioniert unsere. Die Schnittstelle wurde dialogorientiert; die Kontrollen wurden nicht verschoben. Das erlaubt einem Kreditgeber, den Assistenten dort einzusetzen, wo der Umsatz ist, in der Origination und im Servicing, ohne eine Lücke zu öffnen, die ein Aufseher finden würde.</p>
      <h2>5. Kontinuierliche Verbesserung: willkommen, aber sie muss gesteuert werden</h2>
      <p>Entscheidungslogik veraltet, daher hat McKinsey recht, dass kontinuierliche Verbesserung besser ist, als auf das nächste große Release zu warten. Doch die Regeln, die entscheiden, wer finanziert wird und zu welchen Konditionen, dürfen sich nicht stillschweigend selbst ändern. Ein Aufseher wird fragen, was die Richtlinie vor achtzehn Monaten entschieden hat, warum, und ob sie genehmigt wurde, bevor sie einen Kunden betraf. Verbesserung muss also gesteuert werden: die KI schlägt eine Änderung vor, ein Mensch genehmigt sie, die Plattform übernimmt sie als neue, benannte Version, und jede frühere Entscheidung kann unter der Version wiederholt werden, die zu der Zeit galt. Das ist kontinuierliche Verbesserung, die ein regulierter Kreditgeber tatsächlich betreiben kann, mit dem stabilen Kern, der laut der vorsichtigeren Lesart von McKinsey Bestand haben muss.</p>
      <h2>Das Muster, und was dagegen zu tun ist</h2>
      <p>Der rote Faden durch alle fünf Punkte ist derselbe. Die KI-native Zukunft, die McKinsey beschreibt, wird nicht durch den Zugang zu KI gebremst. Sie wird durch die Plattform entschieden, die ein Unternehmen betrieb, bevor die KI kam. Die 40 Prozent, die den Wert erfassen, sind jene, deren Plattform konfiguriert, nicht neu gebaut wird, jedes Mal gleich entscheidet und nachweisen kann, was sie getan hat. Die übrigen führen die KI ein und sehen wenig davon im Ergebnis ankommen.</p>
      <p>Der nützlichste nächste Schritt ist also keine KI-Auswahlliste. Es ist ein ehrlicher Blick auf die eigene Plattform. Werden neue Produkte konfiguriert oder von Grund auf programmiert. Sind Ihre Kontrollen in die Plattform eingebaut oder in jeden Prozess von Hand hineingeschrieben. Kann einer Migration vertraut und sie zurückverfolgt werden. Erbt die dialogorientierte Ebene Ihre Berechtigungen unverändert. Kann jede Änderung einer Kreditrichtlinie auf Abruf reproduziert werden. Die Antworten auf diese Fragen, nicht das Modell, das Sie lizenzieren, entscheiden, ob KI Ihren Gewinn erreicht. Wir haben nicht mehr KI eingeführt als der Markt. Wir haben die Plattform gebaut, auf der KI sich auszahlt, und in der regulierten Nichtbanken-Kredit- und Leasingwelt ist das der Unterschied zwischen dem Erfassen des Werts, den McKinsey beschreibt, und dem bloßen Darüber-Lesen.</p>
    </div>
  );
}

function Fr() {
  return (
    <div className="prose-paper">
      <p>L&apos;analyse de McKinsey de janvier 2026, <a href="https://www.mckinsey.com/capabilities/mckinsey-technology/our-insights/the-end-of-erp-as-we-know-it-five-ways-ai-is-disrupting-erp" target="_blank" rel="noopener noreferrer">The end of ERP as we know it? Five ways AI is disrupting ERP</a>, offre la lecture la plus claire de l&apos;endroit où l&apos;IA change l&apos;économie de la plateforme d&apos;entreprise, et nous y souscrivons entièrement. L&apos;enjeu est considérable : un effort de mise en œuvre réduit de moitié environ, une refonte des processus en quelques jours, une migration des données qui n&apos;est plus le goulot d&apos;étranglement, une porte d&apos;entrée conversationnelle à la place des menus, et un système qui s&apos;améliore en continu plutôt que par grandes versions. Le piège figure dans la même analyse. Les entreprises qui intègrent l&apos;IA au cœur de leur système augmentent leur EBIT d&apos;environ 5 pour cent, et pourtant seulement environ 40 pour cent des organisations en tirent une quelconque valeur à l&apos;échelle de l&apos;entreprise. La valeur est réelle, et l&apos;essentiel est laissé sur la table.</p>
      <p>La question pour une activité de prêt ou de leasing n&apos;est donc pas de savoir si les cinq évolutions arrivent. Elles arrivent. La question est de savoir ce qui distingue les 40 pour cent qui captent la valeur des 60 pour cent qui n&apos;y parviennent pas. D&apos;après notre expérience, la réponse n&apos;est pas l&apos;IA qu&apos;une entreprise achète, puisque chacun peut acheter les mêmes modèles. C&apos;est la plateforme sur laquelle l&apos;IA fonctionne. Chaque évolution ne porte ses fruits que là où la plateforme est conçue pour être configurée plutôt que reconstruite, pour décider de la même manière à chaque fois, et pour prouver ce qu&apos;elle a fait. C&apos;est la plateforme que nous exploitons déjà. Ci-dessous, nous reprenons chacun des cinq points de McKinsey, nous y souscrivons, et nous nommons la condition unique qui détermine s&apos;il atteint le résultat net chez un prêteur réglementé.</p>
      <h2>1. Mise en œuvre : la rapidité est réelle, mais elle n&apos;est pas accessible à tous de la même façon</h2>
      <p>McKinsey a raison de dire que l&apos;IA réduit de moitié environ le temps et l&apos;effort nécessaires pour déployer une plateforme. Cet enjeu n&apos;est pas accessible à tous de la même façon. Il bénéficie aux opérateurs dont la plateforme est configurée, et non reconstruite, pour chaque nouvelle institution, car l&apos;IA y accélère une installation propre et reproductible plutôt que de démêler des années de code sur mesure. Nous mettons un nouveau prêteur en production en configurant des règles sur une plateforme partagée unique, et nous menons la migration des données comme une étape standard et reproductible plutôt que comme un projet que nous réinventons à chaque fois. La rapidité que décrit McKinsey est donc notre modèle opérationnel, et non une aspiration. Sur un système fortement personnalisé, la même IA ne fait que rogner les marges, ce qui explique précisément pourquoi la valeur se concentre dans une minorité d&apos;entreprises plutôt que d&apos;atteindre tout le monde.</p>
      <h2>2. Conception des processus : dans le prêt, un processus est un contrôle, pas seulement un flux de travail</h2>
      <p>Les agents peuvent désormais proposer un mode de fonctionnement cible en quelques jours, et c&apos;est un véritable atout. Mais chez un prêteur réglementé, un processus porte les contrôles de l&apos;institution : qui peut approuver, qui peut engager l&apos;entreprise et jusqu&apos;à quelle limite, où une opération doit s&apos;arrêter. Laissez un agent concevoir librement et il supprimera discrètement un contrôle qu&apos;il interprète comme un frein, et l&apos;entreprise aura cédé quelque chose dont elle répond devant son régulateur, sans que personne ne l&apos;ait décidé. L&apos;atout n&apos;est sûr que lorsque l&apos;agent formule ses propositions dans un modèle où ces contrôles sont fixes et ne peuvent être déplacés sans une décision enregistrée et approuvée. C&apos;est ainsi que nous procédons : l&apos;agent accélère la conception, la plateforme maintient les contrôles en place, et chaque changement est journalisé. Des jours au lieu de semaines, avec la posture de contrôle intacte.</p>
      <h2>3. Migration : la rapidité ne compte que si l&apos;on peut faire confiance aux données ensuite</h2>
      <p>McKinsey a raison de dire que l&apos;IA supprime l&apos;essentiel du nettoyage manuel des données qui ralentit ces programmes. Le piège est que la rapidité ne paie que si l&apos;on peut faire confiance au résultat, car dans le prêt ces données alimentent les décisions de crédit en temps réel et le provisionnement dès le premier jour. Une migration rapide mais qui ne peut être retracée jusqu&apos;à la source ni reproduite est un risque qui attend l&apos;examinateur. Notre plateforme refuse les données qui ne correspondent pas au moment du chargement, et un portefeuille migré peut être rejoué pour reproduire les mêmes classifications et provisions. L&apos;IA raccourcit donc la partie qui prenait auparavant des mois, et l&apos;entreprise arrive avec un portefeuille qu&apos;elle peut défendre. Sur un système dépourvu d&apos;une telle discipline, l&apos;IA accélère la moitié facile et la moitié difficile revient sous forme de revue manuelle.</p>
      <h2>4. Langage naturel : la porte d&apos;entrée change, les contrôles non</h2>
      <p>L&apos;interface conversationnelle transforme en simple produit de base les écrans élaborés que les fournisseurs ont mis deux décennies à rendre captifs, exactement comme l&apos;avance la lecture la plus audacieuse de McKinsey. Chez un prêteur réglementé, elle n&apos;est sûre que si elle ne peut rien faire qu&apos;un humain à ce poste ne pourrait faire : elle agit par le biais des opérations existantes et autorisées de la plateforme, et une demande que l&apos;utilisateur n&apos;est pas autorisé à formuler échoue pour l&apos;assistant tout comme elle échouerait pour la personne, et elle est enregistrée de la même manière. C&apos;est ainsi que fonctionne la nôtre. L&apos;interface est devenue conversationnelle ; les contrôles n&apos;ont pas bougé. C&apos;est ce qui permet à un prêteur de placer l&apos;assistant là où se trouve le revenu, dans l&apos;origination et la gestion, sans ouvrir une faille qu&apos;un superviseur trouverait.</p>
      <h2>5. Amélioration continue : bienvenue, mais elle doit être gouvernée</h2>
      <p>La logique de décision se périme, et McKinsey a donc raison de dire que l&apos;amélioration continue vaut mieux que d&apos;attendre la prochaine grande version. Mais les règles qui décident qui est financé, et à quelles conditions, ne peuvent se modifier d&apos;elles-mêmes en silence. Un superviseur demandera ce que la politique a décidé il y a dix-huit mois, pourquoi, et si cela a été validé avant d&apos;affecter un client. L&apos;amélioration doit donc être gouvernée : l&apos;IA propose un changement, une personne l&apos;approuve, la plateforme l&apos;adopte comme une nouvelle version nommée, et toute décision passée peut être rejouée sous la version qui s&apos;appliquait à l&apos;époque. Voilà une amélioration continue qu&apos;un prêteur réglementé peut réellement mettre en œuvre, avec le cœur stable que la lecture plus prudente de McKinsey juge indispensable de préserver.</p>
      <h2>Le schéma, et ce qu&apos;il convient d&apos;en faire</h2>
      <p>Le fil conducteur des cinq points est le même. L&apos;avenir nativement porté par l&apos;IA que décrit McKinsey n&apos;est pas freiné par l&apos;accès à l&apos;IA. Il est déterminé par la plateforme qu&apos;une entreprise exploitait avant l&apos;arrivée de l&apos;IA. Les 40 pour cent qui captent la valeur sont ceux dont la plateforme est configurée plutôt que reconstruite, décide de la même manière à chaque fois, et peut prouver ce qu&apos;elle a fait. Les autres adoptent l&apos;IA et n&apos;en voient guère atteindre le résultat net.</p>
      <p>L&apos;étape suivante la plus utile n&apos;est donc pas une liste restreinte d&apos;outils d&apos;IA. C&apos;est un examen honnête de votre propre plateforme. Les nouveaux produits sont-ils configurés ou codés de zéro. Vos contrôles sont-ils intégrés à la plateforme ou inscrits à la main dans chaque processus. Une migration peut-elle être digne de confiance et retracée. La couche conversationnelle hérite-t-elle de vos autorisations sans modification. Chaque changement apporté à une politique de crédit peut-il être reproduit à la demande. Les réponses à ces questions, et non le modèle que vous licenciez, déterminent si l&apos;IA atteint votre résultat net. Nous n&apos;avons pas adopté plus d&apos;IA que le marché. Nous avons construit la plateforme sur laquelle l&apos;IA paie, et dans le prêt et le leasing non bancaires réglementés, c&apos;est ce qui fait la différence entre capter la valeur que décrit McKinsey et seulement en lire le récit.</p>
    </div>
  );
}

function It() {
  return (
    <div className="prose-paper">
      <p>L&apos;analisi di McKinsey del gennaio 2026 <a href="https://www.mckinsey.com/capabilities/mckinsey-technology/our-insights/the-end-of-erp-as-we-know-it-five-ways-ai-is-disrupting-erp" target="_blank" rel="noopener noreferrer">The end of ERP as we know it? Five ways AI is disrupting ERP</a> è la lettura più chiara di dove l&apos;IA cambia l&apos;economia della piattaforma aziendale, e siamo d&apos;accordo su tutto. Il premio è ampio: sforzo di implementazione ridotto all&apos;incirca della metà, riprogettazione dei processi in pochi giorni, migrazione dei dati che non è più il vincolo principale, una porta d&apos;accesso conversazionale al posto dei menu, e un sistema che migliora in modo continuo anziché con rilasci a effetto. Il problema si trova nella stessa analisi. Le aziende che integrano l&apos;IA nel nucleo aumentano l&apos;EBIT di circa il 5 percento, eppure solo circa il 40 percento delle organizzazioni cattura un qualsiasi valore a livello aziendale. Il valore è reale, e la maggior parte di esso viene lasciata sul tavolo.</p>
      <p>Quindi la domanda per un&apos;azienda di credito o di leasing non è se i cinque cambiamenti stiano arrivando. Stanno arrivando. È cosa distingue il 40 percento che cattura il valore dal 60 percento che non lo fa. Per nostra esperienza la risposta non è l&apos;IA che un&apos;azienda acquista, dato che tutti possono acquistare gli stessi modelli. È la piattaforma su cui l&apos;IA gira. Ogni cambiamento dà i suoi frutti solo dove la piattaforma è costruita per essere configurata anziché ricostruita, per decidere sempre allo stesso modo, e per dimostrare ciò che ha fatto. Quella è la piattaforma che già utilizziamo. Di seguito affrontiamo a uno a uno i cinque punti di McKinsey, ci troviamo d&apos;accordo, e indichiamo l&apos;unica condizione che decide se ciascuno raggiunge il risultato economico in un istituto di credito regolamentato.</p>
      <h2>1. Implementazione: la velocità è reale, ma non è disponibile in modo uniforme</h2>
      <p>McKinsey ha ragione nel dire che l&apos;IA riduce all&apos;incirca della metà il tempo e lo sforzo per avviare una piattaforma. Quel premio non è disponibile in modo uniforme. Va agli operatori la cui piattaforma è configurata, non ricostruita, per ogni nuova istituzione, perché lì l&apos;IA accelera una configurazione pulita e ripetibile anziché districare anni di codice personalizzato. Avviamo un nuovo istituto di credito configurando le regole su un&apos;unica piattaforma condivisa, e gestiamo la migrazione dei dati come un passaggio standard e ripetibile anziché come un progetto che reinventiamo ogni volta. Quindi la velocità che McKinsey descrive è il nostro modello operativo, non un&apos;aspirazione. Su un sistema fortemente personalizzato la stessa IA si limita a smussare i bordi, ed è esattamente per questo che il valore si concentra in una minoranza di aziende anziché raggiungere tutti.</p>
      <h2>2. Progettazione dei processi: nel credito, un processo è un controllo, non solo un flusso di lavoro</h2>
      <p>Gli agenti possono ora proporre un modo di lavorare obiettivo in pochi giorni, e questo è un premio autentico. Ma in un istituto di credito regolamentato un processo porta con sé i controlli dell&apos;istituzione: chi può approvare, chi può impegnare l&apos;azienda e fino a quale limite, dove un&apos;operazione deve fermarsi. Lasciate che un agente progetti liberamente e rimuoverà silenziosamente un controllo che interpreta come un attrito, e l&apos;azienda ha ceduto qualcosa di cui risponde al proprio supervisore, senza che nessuno l&apos;abbia deciso. Il premio è al sicuro solo quando l&apos;agente propone all&apos;interno di un modello dove quei controlli sono fissi e non possono essere spostati senza una decisione registrata e approvata. È così che lo gestiamo: l&apos;agente accelera la progettazione, la piattaforma mantiene i controlli al loro posto, e ogni modifica è registrata. Giorni anziché settimane, con l&apos;impostazione dei controlli intatta.</p>
      <h2>3. Migrazione: la velocità conta solo se i dati possono essere considerati affidabili dopo</h2>
      <p>McKinsey ha ragione nel dire che l&apos;IA elimina gran parte della pulizia manuale dei dati che rallenta questi programmi. Il problema è che la velocità ripaga solo se il risultato può essere considerato affidabile, perché nel credito quei dati guidano le decisioni di credito in tempo reale e gli accantonamenti fin dal primo giorno. Una migrazione veloce ma che non può essere ricondotta alla fonte o riprodotta è una passività in attesa di un esaminatore. La nostra piattaforma rifiuta i dati che non sono conformi al momento del caricamento, e un portafoglio migrato può essere rieseguito per riprodurre le stesse classificazioni e gli stessi accantonamenti. Quindi l&apos;IA accorcia la parte che prima richiedeva mesi, e l&apos;azienda arriva con un portafoglio che può difendere. Su un sistema privo di tale disciplina, l&apos;IA accelera la metà facile e la metà difficile torna sotto forma di revisione manuale.</p>
      <h2>4. Linguaggio naturale: la porta d&apos;accesso cambia, i controlli no</h2>
      <p>L&apos;interfaccia conversazionale trasforma le schermate elaborate che i fornitori hanno impiegato due decenni a rendere coinvolgenti in una commodity, esattamente come sostiene la lettura più audace di McKinsey. In un istituto di credito regolamentato è al sicuro solo se non può fare nulla che una persona in quella posizione non potrebbe fare: agisce attraverso le operazioni esistenti e autorizzate della piattaforma, e una richiesta che l&apos;utente non è autorizzato a fare fallisce per l&apos;assistente proprio come fallirebbe per la persona, ed è registrata allo stesso modo. È così che funziona la nostra. L&apos;interfaccia è diventata conversazionale; i controlli non si sono spostati. È questo che consente a un istituto di credito di collocare l&apos;assistente dove sono i ricavi, nell&apos;origination e nella gestione, senza aprire una falla che un supervisore troverebbe.</p>
      <h2>5. Miglioramento continuo: benvenuto, ma deve essere governato</h2>
      <p>La logica decisionale si logora, quindi McKinsey ha ragione nel dire che il miglioramento continuo è preferibile all&apos;attesa del prossimo grande rilascio. Ma le regole che decidono chi viene finanziato, e a quali condizioni, non possono cambiarsi silenziosamente da sole. Un supervisore chiederà cosa ha deciso la policy diciotto mesi fa, perché, e se sia stata approvata prima che incidesse su un cliente. Quindi il miglioramento deve essere governato: l&apos;IA propone una modifica, una persona la approva, la piattaforma la adotta come una nuova versione denominata, e qualsiasi decisione passata può essere riprodotta sotto la versione che si applicava all&apos;epoca. Questo è il miglioramento continuo che un istituto di credito regolamentato può davvero gestire, con il nucleo stabile che la lettura più prudente di McKinsey afferma debba perdurare.</p>
      <h2>Lo schema, e cosa farne</h2>
      <p>Il filo conduttore di tutti e cinque i punti è lo stesso. Il futuro nativo dell&apos;IA che McKinsey descrive non è frenato dall&apos;accesso all&apos;IA. È deciso dalla piattaforma che un&apos;azienda utilizzava prima che arrivasse l&apos;IA. Il 40 percento che cattura il valore è quello la cui piattaforma è configurata anziché ricostruita, decide sempre allo stesso modo, e può dimostrare ciò che ha fatto. Il resto adotta l&apos;IA e ne vede ben poco raggiungere il risultato economico.</p>
      <p>Quindi il prossimo passo più utile non è una rosa di soluzioni di IA. È uno sguardo onesto sulla vostra stessa piattaforma. I nuovi prodotti sono configurati o programmati da zero. I vostri controlli sono integrati nella piattaforma o scritti a mano in ciascun processo. Una migrazione può essere considerata affidabile e tracciata. Lo strato conversazionale eredita le vostre autorizzazioni senza modifiche. Ogni modifica a una policy di credito può essere riprodotta su richiesta. Le risposte a queste domande, non il modello che mettete in licenza, decidono se l&apos;IA raggiunge il vostro utile. Non abbiamo adottato più IA del mercato. Abbiamo costruito la piattaforma su cui l&apos;IA ripaga, e nel credito e nel leasing non bancari e regolamentati questa è la differenza tra catturare il valore che McKinsey descrive e limitarsi a leggerne.</p>
    </div>
  );
}
